
spring:
  main:
    banner-mode: off
    lazy-initialization: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    platform: postgres

